### ISSUE TITLE
About Init

### ISSUE THREAD

**Issue by DJ-LYH** [jianhao2016/GPRGNN#10]
![image](https://user-images.githubusercontent.com/65936780/144485489-3dd6f078-c2b8-4c1d-bd62-7f3ecb588772.png)
As you know, the alpha is a float number. 
How could TEMP[alpha] = 1.0 run?
It's confused.

**Comment by elichienxD** [comment]
Hi @DJ-LYH ,

Sorry that we should add more comments to make it more clear. In the case that using SGC-like initialization, we slightly abuse the notation of alpha in this case. That is, we use alpha to denote which step we are putting the weight on. In this case, alpha should be an integer. For example, if you want to initialize GPR weight with peak at step 2 while having potential K steps, then you can set alpha = 2 in this case. I'll add a comment to it to make it more clear.

Please let me know if you have further questions. 

Eli

**Comment by DJ-LYH** [comment]
> Hi @DJ-LYH ,
> 
> Sorry that we should add more comments to make it more clear. In the case that using SGC-like initialization, we slightly abuse the notation of alpha in this case. That is, we use alpha to denote which step we are putting the weight on. In this case, alpha should be an integer. For example, if you want to initialize GPR weight with peak at step 2 while having potential K steps, then you can set alpha = 2 in this case. I'll add a comment to it to make it more clear.
> 
> Please let me know if you have further questions.
> 
> Eli

Get it. Thanks for your reply.
So "SGC-like init" means the model is equal to a SGC at begining? I thought it means init method like SGC before... 
So does other "xxx-like init" also means the model is equal to XXX model at begining? Or means similar init method with XXX model?

**Comment by elichienxD** [comment]
Hi @DJ-LYH,

Yes, the "SGC-like init" means the model will initialize GPR weights in a form of SGC ($\delta_{ik}$ in our paper for the peak at step k). All the "xxx-like init" refers to the initialization of GPR weights $\gamma_k$s.

Eli

**Comment by elichienxD** [comment]
Issue closed. Feel free to reopen if there's any question.
