### ISSUE TITLE
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.

### ISSUE THREAD

**Issue by xihongyang1999** [jianhao2016/GPRGNN#11]
Dear authors,

Thank you for this awesome work. I found the provided examples are very clear. However, I found the following error when I ran the Film Chameleon and Squirrel datasets. 

“RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.”

After removing 'processed' as prompted, I run it again to report the same error. Do you have any idea to deal with this problem?

Thank you.

**Comment by jianhao2016** [comment]
Hi xihong，

It looks pyg has changed the class 'data' and it may be the cause of such error. Attached is the a version set of our testing environment, you can try with them first and if the issues persist, please send me your version set and I will check the loading function again. 

torch==1.4.0+cu100
torch-cluster==1.5.2
torch-geometric==1.6.3
torch-isin==1.0.2
torch-scatter==2.0.4
torch-sparse==0.6.0
torch-spline-conv==1.2.0
torchvision==0.5.0+cu100

Best,
Jianhao

**Comment by elichienxD** [comment]
Issue closed. Feel free to reopen if there's any question.

**Comment by huanghesheng2012** [comment]
I have met the same problem

**Comment by elichienxD** [comment]
Hi everyone @huanghesheng2012  @xihongyang1999 ,

After checking the pull request from @warpmatrix, it seems like there's a quick fix for this issue.

For chameleon and squirrel, you can load graph and node features by using

`dataset = WikipediaNetwork( root='../data/', name=name,geom_gcn_preprocess=False, transform=T.NormalizeFeatures())`

and get the node labels by using

`dataset = WikipediaNetwork( root='../data/', name=name,geom_gcn_preprocess=True, transform=T.NormalizeFeatures())`

Note that using the graph from `geom_gcn_preprocess=False` is necessary for reproducing our results and more reasonable, as `geom_gcn_preprocess=True (default)` is pre-processed one using geom-gcn paper.

For Actor(film) dataset, you can directly use 

`dataset = Actor(
            root='../data/film', transform=T.NormalizeFeatures())`

I'll merge the code from @warpmatrix after they fix update their pull request. Before that, this is the quick fix.

Let me know if this work for you or you have any other questions.

Thanks,
Eli

**Comment by elichienxD** [comment]
Hi everyone @huanghesheng2012 @xihongyang1999 ,

Just a quick update. Now the issue is fixed and we no longer need the older version of PyG. Thanks for the contribution from @warpmatrix !!

Additionally, I add `Reproduce_GPRGNN.sh` which can be used to easily reproduce our results in Table 2 for GPRGNN.

Let me know if there's any other problems!

Thanks,
Eli
