### ISSUE TITLE
What's WS init?

### ISSUE THREAD

**Issue by hazdzz** [jianhao2016/GPRGNN#12]
In your code, there 5 different init modes. What's WS init? Could you explain how to use this mode? More specifically, how to determine the gamma in this mode?
<img width="180" alt="Screen Shot 2021-12-13 at 20 35 03" src="https://user-images.githubusercontent.com/11409688/145814143-d3742897-b115-4776-9015-e57fef4c7627.png">

**Comment by elichienxD** [comment]
Hi @hazdzz ,

This mode gives you an option to pass your own initialization of GPR weights in it. In our paper, we did not use this mode, but you can try it out by yourself. The pre-determined gamma could be obtained in a transfer learning fashion or any other way you like.

Eli
