### ISSUE TITLE
Graph Spectral Coefficient Initialization

### ISSUE THREAD

**Issue by joneswong** [jianhao2016/GPRGNN#15]
Hi, I noticed that the coefficient of the K-th order term is initialized in a way that is different from others. In one of my experiments, the learned coefficient of the K-th order term thus is much larger than others (alpha=0.1). Could you tell me why this is needed? Thanks!

https://github.com/jianhao2016/GPRGNN/blob/dc246833865af87ae5d4e965d189608f8832ddac/src/GNN_models.py#L36

**Comment by elichienxD** [comment]
Hi @joneswong ,

This follows the original PPR formulation when truncated at step K. This makes the coefficient sum equal to 1. Note that in APPNA they also use this rule. More specifically:

$$ \sum_{k=0}^{K-1} \alpha (1-\alpha)^k + (1-\alpha)^K = \alpha\frac{1-(1-\alpha)^K}{1-(1-\alpha)} + (1-\alpha)^K = 1$$

Let me know if you have further questions.

Best,
Eli

**Comment by joneswong** [comment]
Thanks for your explanation! I just found that this works better than that multiplies $\alpha$ to the last term as previous terms.
