### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by uestclbh** [jianhao2016/GPRGNN#16]
why your edge number is different from Gemo-GNN?

**Comment by uestclbh** [comment]
sorry，spelling mistake. I mean "GEOM-GCN: GEOMETRIC GRAPH CONVOLUTIONAL
NETWORKS", this work

**Comment by elichienxD** [comment]
Hi @uestclbh ,

If I remember correctly, we take the raw data directly from their github repo. Notably, they do have a preprocessing step which makes the graph different. See Issue #14 for more details. Could you check if the solution there resolves your issue?

Thanks,
Eli

**Comment by uestclbh** [comment]
Hi,&nbsp;Eli
I have received your reply and thank you for answering our confusion.
Due to busy schedule, I did not reply in time. I wish you success in your studies.


Good luck!
uestclbh
&nbsp;


李秉恒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eli ***@***.***&gt;; 
发送时间: 2022年11月5日(星期六) 上午6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jianhao2016/GPRGNN] Dataset (Issue #16)





 
Hi @uestclbh ,
 
If I remember correctly, we take the raw data directly from their github repo. Notably, they do have a preprocessing step which makes the graph different. See Issue #14 for more details. Could you check if the solution there resolves your issue?
 
Thanks,
 Eli

**Comment by elichienxD** [comment]
Hi @uestclbh ,

Great! I'll close the issue for now but feel free to reopen it if you have further questions.

Best,
Eli
