### ISSUE TITLE
About random seeds

### ISSUE THREAD

**Issue by Lukangkang123** [jianhao2016/GPRGNN#19]
It is well known that the node classification task of these datasets is greatly affected by randomness, but I don't see any random seed settings in your code. Therefore, I would like to ask why not fix the random seed for reproducibility?

**Comment by elichienxD** [comment]
Hi @Lukangkang123 ,

Thanks for raising the question. At the time we conduct the experiment, we thought that the randomness should not affect too much as long as we are averaged over sufficient independent trials/runs. If I remember correctly, we use 100 independent runs and the results are quite consistent. Did you observe a huge discrepancy between our reported results and your reproduced results? 

While I do agree that using fixed seed guarantees 100% reproducibility, I also feel that the methods/results should be consistent over arbitrary random seeds when averaging over a sufficient number of runs. Please do let me know if there is a huge discrepancy and I'll try my best to fix the issue.

Best,
Eli

**Comment by Lukangkang123** [comment]
> Hi @Lukangkang123 ,
> 
> Thanks for raising the question. At the time we conduct the experiment, we thought that the randomness should not affect too much as long as we are averaged over sufficient independent trials/runs. If I remember correctly, we use 100 independent runs and the results are quite consistent. Did you observe a huge discrepancy between our reported results and your reproduced results?
> 
> While I do agree that using fixed seed guarantees 100% reproducibility, I also feel that the methods/results should be consistent over arbitrary random seeds when averaging over a sufficient number of runs. Please do let me know if there is a huge discrepancy and I'll try my best to fix the issue.
> 
> Best, Eli

Thanks for your answer, I have no more questions.
