### ISSUE TITLE
About the assert of parameter theta in cSBM_dataset.py

### ISSUE THREAD

**Issue by PonderLY** [jianhao2016/GPRGNN#2]
In Line 104 of cSBM_dataset.py, assert (theta >= 0) and (theta <= 1). This makes Lambda always non-negative. Based on the GPRGNN paper, Lambda (or phi) could be negative to demonstrate heterophily. I think theta should be in the range of [-1, 1]. Please check it.

**Comment by jianhao2016** [comment]
Hi PonderLY, thank you for your interests in our work and bringing up the issue. I have updated the range of theta to [-1, 1]. Though, the heterophily cSBM dataset can still be generate with specified lambda, mu, n, p and epsilon. The choice of parameters can be found in supplement of our paper.
