### ISSUE TITLE
About reproducing the cSBM datasets

### ISSUE THREAD

**Issue by joneswong** [jianhao2016/GPRGNN#5]
Hi jianhao,
    I noticed that the `avg_degree` is set to be `5` in `create_cSBM_dataset.sh`. However, I cannot figure out what is the value of `avg_degree` used in your paper.
    If we want to reproduce the cSBM datasets used in your paper exactly, how about
 
```bash
phis=(-1.0 -0.75 -0.5 -0.25 0.0 0.25 0.5 0.75 1.0)
for (( i=0; i<${#phis[@]}; i++ ))
do
  python cSBM_dataset.py --phi ${phis[$i]} \
      --name cSBM_phi_${phis[$i]} \
      --root ../data/ \
      --num_nodes 5000 \
      --num_features 2000 \
      --avg_degree 5 \
      --epsilon 3.25 \
      --train_percent 0.025 \
done

(I supplemented the argument `train_percent` accordingly, but the dense splits needs to modify your utility code snippets)

**Comment by jianhao2016** [comment]
Hi joneswong, 

Sorry for the delay in response. Yes, you can use `avg_degree = 5` by default to regenerate the cSBM dataset. And the script you attached seems fine to me.

Best,
Jianhao
