### ISSUE TITLE
Difference between GPR-GNN and ChebyNet

### ISSUE THREAD

**Issue by zhuo931077127** [jianhao2016/GPRGNN#6]
Formally，the only difference between GPR-GNN, which represented as <a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{Z}=\sum_{k=0}^{K}&space;\gamma_{k}&space;\mathbf{H}^{(k)}&space;=&space;\sum_{k=0}^{K}&space;\gamma_{k}&space;(\tilde{\mathbf{A}}_{\mathrm{sym}}&space;)^k\mathbf{H}^{(0)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{Z}=\sum_{k=0}^{K}&space;\gamma_{k}&space;\mathbf{H}^{(k)}&space;=&space;\sum_{k=0}^{K}&space;\gamma_{k}&space;(\tilde{\mathbf{A}}_{\mathrm{sym}}&space;)^k\mathbf{H}^{(0)}" title="\mathbf{Z}=\sum_{k=0}^{K} \gamma_{k} \mathbf{H}^{(k)} = \sum_{k=0}^{K} \gamma_{k} (\tilde{\mathbf{A}}_{\mathrm{sym}} )^k\mathbf{H}^{(0)}" /></a>, and Spectral GraphCNN <a href="https://www.codecogs.com/eqnedit.php?latex=Z&space;=&space;\mathbf{U}&space;g_{\gamma,&space;K}(\mathbf{\Lambda})&space;\mathbf{U}^{T}X&space;=&space;(\sum^K_{k=0}\gamma_k&space;L^k)X" target="_blank"><img src="https://latex.codecogs.com/gif.latex?Z&space;=&space;\mathbf{U}&space;g_{\gamma,&space;K}(\mathbf{\Lambda})&space;\mathbf{U}^{T}X&space;=&space;(\sum^K_{k=0}\gamma_k&space;L^k)X" title="Z = \mathbf{U} g_{\gamma, K}(\mathbf{\Lambda}) \mathbf{U}^{T}X = (\sum^K_{k=0}\gamma_k L^k)X" /></a> is replacing L with A_sym, right?

**Comment by elichienxD** [comment]
Hi @zhuo931077127 

Thanks for being interested in our work. One difference is as you pointed our, the other is that we use H^{(0)} = MLP(X) but not X. Note that in our paper we argue that jointly training MLP part with learnable GPR weights is crucial.

Sorry for the late reply, please let me know if this resolve your question.

Thanks,
Eli

**Comment by zhuo931077127** [comment]
Thanks for your reply.
