### ISSUE TITLE
Question about the theorem 4.2

### ISSUE THREAD

**Issue by mdanb** [jianhao2016/GPRGNN#8]
For theorem 4.2:
If the gradients of the gammas have the same sign for some k', why does that imply that the magnitude of the gammas approaches 0 for k >= k' when oversmoothing happens?

For theorem A.1:
You mention the following:
![Screenshot from 2021-09-26 17-23-32](https://user-images.githubusercontent.com/37456158/134824618-80497e88-932b-4771-9033-ee05d9c9b403.png)
But in the example you mention with Kronecker delta, it seems like inequality (a) does not hold, since you would get 1 for |lambda|^0 = 1 on the LHS and |lambda|^1 < 1 on RHS. If lambda is equal to 1, then sure, this works. But it seems like your initial goal was to show:
![Screenshot from 2021-09-26 17-27-11](https://user-images.githubusercontent.com/37456158/134824692-d4961afb-ae09-4331-be52-720b9ea361c4.png)

**Comment by elichienxD** [comment]
Hi @mdanb ,

Thanks for the great questions! I apologize for my late reply as I'm pretty busy recently. 

Regarding your first question. Note that in the paragraph below Theorem 4.2 we argue that "with a suitable learning rate", the magnitude of gammas will keep decaying. Although we couldn't rigorously prove this (and thus we didn't include it in the theorem), this should be true for most cases.

Regarding your second question. Yes, you're right. This should be fixed as follows:
`\sum_{k=0}^K \gamma_k |\lambda|^k \leq \gamma_0 + \sum_{k=1}^K \gamma_k |\lambda|.`

[That is, we have to distinguish the \gamma_0 term!]

Hence, for now we have two corner cases (which makes the equality hold, this is yet another typo in our manuscript): One is \gamma_k = \delta_{k0}, the other one is \gamma_k = \delta_{k1} (and of course, their combinations). So the theorem should be
![image](https://user-images.githubusercontent.com/46387845/135032200-b8c2ceff-e944-48cc-a5cd-a64ce2da08db.png)

Nevertheless, the main point of this theorem still holds: most designs (and especially APPNP) are low pass graph filters. 

Thank you for pointing out this issue. We will fix it and update our arxiv version. Also, if you don't mind I would like to write an acknowledgment in our revision to thank you for pointing out this issue. Please drop me an email with your name if you don't mind :). Also, let me know if you have other questions. If not, I'll close the issue in a few days.

Thanks,
Eli
