### ISSUE TITLE
About gamma initialization

### ISSUE THREAD

**Issue by hazdzz** [jianhao2016/GPRGNN#9]
In your code, you use zero init for TEMP first, then replace elements in TEMP. I have confused about this operation. Why do you raplace elements in initialized tensor by fixed parameters?

<img width="442" alt="Screen Shot 2021-10-21 at 20 59 27" src="https://user-images.githubusercontent.com/11409688/138283309-5f3233b8-7369-4beb-879a-312be9dfd337.png">

**Comment by jianhao2016** [comment]
Hi hazdzz, 

Sorry for the delayed response. The reset_parameters function inside the GPR_prop class won't be called in the model, and the actual GPR weight will be initialized according to self.Init. It was just a legacy function from our previous implementation and we will remove it in the next commit. Thank you for pointing out!

Best,
Jianhao.
